@startuml Manage Massage (GET)

header Massage Reservation System
footer Page %page% of %lastpage%
title "Manage Massage (GET ALL)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:massages" as routerMassages
participant "<<controllers>>\n:massages" as controllersMassages
participant "<<model>>\n:Massage" as modelMassage
database "<<MongoDB>>\n:massages" as MassagesDatabase

client->server ++:req.get('/massages')
server->routerMassages ++:app.use('/massages',massages)
routerMassages -> controllersMassages ++:getMassages()
controllersMassages->modelMassage ++:findAllMassage()
modelMassage ->MassagesDatabase ++: MassageSchema
MassagesDatabase --> modelMassage --: massage
controllersMassages <-- modelMassage --:massage
controllersMassages->client --:response

@enduml
